{{- if not .Values.minio.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mvp-training.fullname" . }}-secret
  labels:
    {{- include "mvp-training.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.minio.accessKey }}
  minio-access-key: {{ .Values.minio.accessKey | quote }}
  {{- end }}
  {{- if .Values.minio.secretKey }}
  minio-secret-key: {{ .Values.minio.secretKey | quote }}
  {{- end }}
  {{- if .Values.backend.callbackToken }}
  backend-callback-token: {{ .Values.backend.callbackToken | quote }}
  {{- end }}
{{- end }}
