{{- if .Values.training.enabled -}}
{{- if .Values.training.namespace }}
{{- if ne .Values.training.namespace "default" }}
# Create training namespace if it doesn't exist
# Note: In production, namespace is usually pre-created by cluster admin
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.training.namespace }}
  labels:
    {{- include "vision-ai.training.labels" . | nindent 4 }}
    purpose: ml-training
{{- end }}
{{- end }}
{{- end }}
