{{- if and .Values.training.enabled .Values.training.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vision-ai.training.serviceAccountName" . }}
  namespace: {{ include "vision-ai.training.namespace" . }}
  labels:
    {{- include "vision-ai.training.labels" . | nindent 4 }}
  {{- with .Values.training.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
