# NodePort Services for Observability Stack
# Apply after Helm deployments to enable localhost access
#
# Usage:
#   kubectl apply -f nodeports.yaml

---
# Prometheus NodePort
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: kube-prometheus-stack-prometheus
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-stack-prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
    protocol: TCP
    name: http-web

---
# Grafana NodePort
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prometheus-stack
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prometheus-stack
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30030
    protocol: TCP
    name: http-web

---
# Loki NodePort (if using separate Loki deployment)
apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  namespace: observability
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
  ports:
  - port: 3100
    targetPort: 3100
    nodePort: 30100
    protocol: TCP
    name: http
