kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # MLflow
  - containerPort: 30500
    hostPort: 30500
    protocol: TCP
  # MinIO API
  - containerPort: 30900
    hostPort: 30900
    protocol: TCP
  # MinIO Console
  - containerPort: 30901
    hostPort: 30901
    protocol: TCP
  # Prometheus
  - containerPort: 30090
    hostPort: 30090
    protocol: TCP
  # Grafana
  - containerPort: 30030
    hostPort: 30030
    protocol: TCP
  # Backend API (if needed)
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
